version: '2.0'

services:

  mysqldb:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:

      MYSQL_ROOT_PASSWORD: root